"""Generate deterministic per-artifact knowledge summary documents."""

from __future__ import annotations

from pathlib import Path
from typing import Any, Dict, Iterable

from .paths import PROJECT_ROOT


def _bullets(items: Iterable[Any]) -> str:
    values = [str(item) for item in items if item is not None and str(item).strip()]
    return "\n".join(f"- {value}" for value in values) if values else "- None identified"


def _value(value: Any, default: str = "Not available") -> str:
    if value is None or str(value).strip() == "":
        return default
    return str(value)


def render_artifact_summary(
    review: Dict[str, Any],
    profile: Dict[str, Any] | None = None,
    source_path: str | None = None,
) -> str:
    """Render one artifact review as a stable, human-readable Markdown document."""
    profile = profile or {}
    identification = review.get("artifact_identification", {})
    selection = review.get("parser_selection", {})
    execution = review.get("parser_execution", {})

    file_name = _value(identification.get("file_name"), review.get("artifact_id", "unknown"))
    resolved_path = source_path or identification.get("source_path") or profile.get("source_path") or file_name
    source_type = _value(identification.get("source_type"), profile.get("source_type", "unknown"))
    artifact_kind = _value(identification.get("artifact_kind"), profile.get("artifact_kind", "unknown"))
    parser = _value(selection.get("parser"), "Not selected")
    parser_status = _value(execution.get("status"), "NOT_EXECUTED")
    review_status = _value(review.get("status"))
    confidence = review.get("confidence")
    confidence_text = _value(confidence, "Not assessed")

    dependencies = review.get("dependencies") or profile.get("dependencies") or []
    business_rules = review.get("business_rules") or profile.get("business_rules") or []
    key_findings = review.get("key_findings") or []
    semantic_gaps = review.get("semantic_gaps") or []
    evidence = review.get("evidence_candidates") or []

    entity_count = profile.get("entity_count")
    relationship_count = profile.get("relationship_count")

    lines = [
        f"# Knowledge Summary — {file_name}",
        "",
        "> Generated by the KAIRIX Knowledge Engineering Agent from deterministic metadata and the available artifact review.",
        "",
        "## Artifact Identity",
        "",
        f"- **Artifact ID:** {_value(review.get('artifact_id'))}",
        f"- **Source Path:** {_value(resolved_path)}",
        f"- **Source type:** {source_type}",
        f"- **Artifact kind:** {artifact_kind}",
        f"- **Review status:** {review_status}",
        "",
        "## Parser",
        "",
        f"- **Selected parser:** {parser}",
        f"- **Execution status:** {parser_status}",
        "",
        "## Purpose",
        "",
        _value(review.get("purpose") or profile.get("purpose")),
        "",
        "## Summary",
        "",
        _value(review.get("summary") or profile.get("purpose")),
        "",
        "## Key Findings",
        "",
        _bullets(key_findings),
        "",
        "## Dependencies",
        "",
        _bullets(dependencies),
        "",
        "## Business Rules",
        "",
        _bullets(business_rules),
        "",
        "## Evidence References",
        "",
        _bullets(evidence),
        "",
        "## Semantic Gaps",
        "",
        _bullets(semantic_gaps),
        "",
        "## Confidence",
        "",
        f"- **Confidence:** {confidence_text}",
        f"- **Deeper analysis required:** {_value(review.get('needs_deeper_analysis'), 'Not assessed')}",
        f"- **Reason:** {_value(review.get('reason'), 'None provided')}",
        "",
        "## Extracted Structure",
        "",
        f"- **Entities:** {_value(entity_count, 'Not available')}",
        f"- **Relationships:** {_value(relationship_count, 'Not available')}",
        "",
    ]
    return "\n".join(lines)


def write_single_summary(
    artifact_id: str,
    review: Dict[str, Any],
    profile: Dict[str, Any] | None = None,
    output_dir: Path | None = None,
    source_path: str | None = None,
) -> Path:
    """Generate and write ONLY the summary document for the requested artifact."""
    out_dir = output_dir or (PROJECT_ROOT / "output" / "knowledge" / "summaries")
    out_dir.mkdir(parents=True, exist_ok=True)

    identification = review.get("artifact_identification", {})
    file_name = source_path or identification.get("file_name") or artifact_id
    stem = Path(str(file_name)).stem
    if stem.endswith("_metadata"):
        stem = stem[:-9]
    safe_name = stem.replace(" ", "_")

    target = out_dir / f"{safe_name}_summary.md"
    content = render_artifact_summary(review, profile, source_path=source_path)
    target.write_text(content, encoding="utf-8")
    return target


def write_artifact_summaries(
    enrichment: Dict[str, Any],
    output_dir: Path,
) -> list[Path]:
    """Write one Markdown summary per artifact review and return created paths."""
    output_dir.mkdir(parents=True, exist_ok=True)
    profiles = {item.get("artifact_id"): item for item in enrichment.get("artifact_profiles", [])}
    created: list[Path] = []

    for review in enrichment.get("artifact_reviews", []):
        artifact_id = review.get("artifact_id", "unknown")
        identification = review.get("artifact_identification", {})
        file_name = identification.get("file_name") or artifact_id
        stem = Path(str(file_name)).stem
        if stem.endswith("_metadata"):
            stem = stem[:-9]
        safe_name = stem.replace(" ", "_")
        target = output_dir / f"{safe_name}_summary.md"
        target.write_text(
            render_artifact_summary(review, profiles.get(artifact_id)),
            encoding="utf-8",
        )
        created.append(target)

    return created
